parser: babel-eslint
env:
  browser: true
  es6: true
extends: airbnb-base
plugins:
  - html
  - import
parserOptions:
  sourceType: module
rules:
  import/no-unresolved:
    - error
    -
      ignore:
        - 'gifshot'
